# .readthedocs.yml
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  commands:
    - pip install --no-cache-dir -r docs/requirements-docs.txt
    - python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml

python:
  install:
    - requirements: docs/requirements-docs.txt

mkdocs:
  configuration: mkdocs.yml
